## Name : Ishwer Kumar Yadav

## Assingment : 2

### NumPy Task

### Q1 : Create a 5x5 matrix with row values ranging from 0 to 4
### Ans

In [2]:
matrix = []
for i in range(5):
    row = []
    for j in range(5):
        row.append(i)
        matrix.append(row)
print(matrix)        

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [2, 2, 2, 2, 2], [2, 2, 2, 2, 2], [2, 2, 2, 2, 2], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3], [3, 3, 3, 3, 3], [3, 3, 3, 3, 3], [3, 3, 3, 3, 3], [3, 3, 3, 3, 3], [4, 4, 4, 4, 4], [4, 4, 4, 4, 4], [4, 4, 4, 4, 4], [4, 4, 4, 4, 4], [4, 4, 4, 4, 4]]


### Alternatively, you could use a list comprehension to create the matrix in a single line of code:

In [5]:
matrix = [[i for j in range(5)] for i in range(5)]
print(matrix)

[[0, 0, 0, 0, 0], [1, 1, 1, 1, 1], [2, 2, 2, 2, 2], [3, 3, 3, 3, 3], [4, 4, 4, 4, 4]]


### Q2 : Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
### Ans    

In [2]:
import numpy as np

a = np.array([[1,1,1],[1,1,1]])
b = np.array([2,3])

res = np.multiply(a,b[:, None])

print(res)

[[2 2 2]
 [3 3 3]]


### Q3 : What is the result of the following expression?
### Ans

In [4]:
0 * np.nan

nan

In [5]:
np.nan == np.nan

False

In [6]:
np.inf > np.nan

False

In [7]:
np.nan - np.nan

nan

In [8]:
np.nan in set([np.nan])

True

In [9]:
0.3 == 3 * 0.1

False

### Q4 : Create a 10x10 array with random values and find the minimum and maximum values
### Ans

In [17]:
import numpy as np

x = np.random.random((10,10))
print('Original array:')
print(x)
xmin , xmax = x.min(),x.max()
print('printing minimum value and maximum value')
print(xmin,xmax)

Original array:
[[1.44856065e-01 5.74254940e-01 4.24138428e-01 3.35766078e-01
  1.16293415e-01 8.57056323e-01 3.65166955e-01 8.61135609e-01
  1.53637248e-01 4.65441499e-01]
 [3.01171949e-01 6.27645117e-01 4.30711155e-01 6.11216783e-02
  6.37918769e-01 8.20761517e-01 6.79824669e-01 9.78091876e-01
  4.59547861e-01 2.35828802e-01]
 [1.84173760e-02 1.02049320e-01 6.76291980e-01 9.86879648e-02
  6.80073520e-01 1.94179159e-01 2.62623163e-01 3.20512205e-01
  3.05008447e-02 5.39736512e-01]
 [1.10597087e-02 3.58581767e-01 7.91481110e-01 6.38409824e-01
  8.42614655e-01 1.17869938e-01 1.48222195e-01 2.03736062e-02
  4.45397744e-01 9.76156064e-01]
 [7.14590219e-01 3.49187527e-01 2.26751277e-01 7.73047272e-01
  5.89807992e-01 9.60618964e-01 5.37327309e-01 5.30726824e-02
  7.86146704e-02 6.78754979e-01]
 [8.54974547e-01 4.23162611e-01 5.31595187e-01 1.81750539e-01
  6.66743755e-01 3.63089729e-01 1.40350768e-01 9.37980507e-04
  8.41156034e-01 9.24485284e-01]
 [2.08414959e-01 2.04093766e-01 7.69784768

### Q5 : Create a null vector of size 10 but the fifth value which is 1
### Ans

In [21]:
import numpy as np

null = np.zeros(10)
null[4] = 1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
